property:
  type: dev

server:
  port: 9010
  shutdown: graceful


logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate : debug
#    '[org.springframework]': debug
#    '[org.springframework.web]': debug


spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: mesadm
    password: 1234

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 1000
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
  transaction:
    mode: jdbc


##### Application Config ####
ap:
  info:
    group: FIS
    site: SVM
    env: DEV
    sequence: 1
  worker:
    pool-size:
      core: 5
      max: 50
    capacity: 1000
    name:
      prefix: FIS-ASYNC-
  interface:
    solace:
      host: 52.79.64.176:55555
      vpn: MES
      client:
        username: default
        password: admin
      connect:
        trial-count: 2
      reconnect:
        trial-count: 20
        per-host: 5
    destination:
      send:
        topic: SVM/DEV/EDC/CMN/00
      receive:
        queue: SVM_DEV_FIS_CMN
        init: SVM/DEV/FIS/CMN/RELOAD
  shutdown:
    force:
      timeout:
        ms: 1000
    polling:
      interval:
        ms: 10