-- MESADM.TN_POS_EQP definition

CREATE TABLE "MESADM"."TN_POS_EQP"
(	"OBJ_ID" VARCHAR2(100),
     "SITE_ID" VARCHAR2(40),
     "EQP_ID" VARCHAR2(40),
     "EQP_NM" VARCHAR2(40),
     "EQP_CLS_ID" VARCHAR2(40),
     "SORTER_MODE_YN" VARCHAR2(1),
     "STAT_CD" VARCHAR2(40),
     "PREV_STAT_CD" VARCHAR2(40),
     "STAT_CD_DT" TIMESTAMP (6),
     "PREV_STAT_DT" TIMESTAMP (6),
     "PROC_STAT_CD" VARCHAR2(40),
     "PREV_PROC_STAT_CD" VARCHAR2(40),
     "PROC_STAT_CD_DT" TIMESTAMP (6),
     "PREV_PROC_STAT_DT" TIMESTAMP (6),
     "CTRL_MODE_CD" VARCHAR2(40),
     "PREV_CTRL_MODE_CD" VARCHAR2(40),
     "CTRL_MODE_DT" TIMESTAMP (6),
     "PREV_CTRL_MODE_DT" TIMESTAMP (6),
     "OPRTN_MODE_CD" VARCHAR2(40),
     "PREV_OPRTN_MODE_CD" VARCHAR2(40),
     "OPRTN_MODE_DT" TIMESTAMP (6),
     "PREV_OPRTN_MODE_DT" TIMESTAMP (6),
     "PROC_LOT_CNT" NUMBER,
     "CPCT" NUMBER(20,10),
     "AUTO_DSP_YN" VARCHAR2(1),
     "INTLK_YN" VARCHAR2(1),
     "FNL_LOT_ID" VARCHAR2(40),
     "SELF_INSP_YN" VARCHAR2(1),
     "FNL_PROD_DEF_ID" VARCHAR2(40),
     "RECIPE_ID" VARCHAR2(100),
     "FNL_TKOUT_DT" TIMESTAMP (6),
     "MAINT_AFT_FST_YN" VARCHAR2(1),
     "LOSS_STAT_CD" VARCHAR2(40),
     "EVNT_NM" VARCHAR2(100),
     "PREV_EVNT_NM" VARCHAR2(100),
     "CSTM_EVNT_NM" VARCHAR2(100),
     "PREV_CSTM_EVNT_NM" VARCHAR2(100),
     "USE_STAT_CD" VARCHAR2(40),
     "RSN_CD" VARCHAR2(40),
     "TRNS_CM" VARCHAR2(4000),
     "CRT_USER_ID" VARCHAR2(40),
     "CRT_DT" TIMESTAMP (6),
     "MDFY_USER_ID" VARCHAR2(40),
     "MDFY_DT" TIMESTAMP (6),
     "FNL_EVNT_DT" TIMESTAMP (6),
     "TID" VARCHAR2(40),
     "FNL_PROC_SGMT_ID" VARCHAR2(40),
     CONSTRAINT "PK_TN_POS_EQP" PRIMARY KEY ("OBJ_ID")
);

COMMENT ON COLUMN MESADM.TN_POS_EQP.OBJ_ID IS '오브젝트ID';
COMMENT ON COLUMN MESADM.TN_POS_EQP.SITE_ID IS '사이트ID';
COMMENT ON COLUMN MESADM.TN_POS_EQP.EQP_ID IS '장비ID';
COMMENT ON COLUMN MESADM.TN_POS_EQP.EQP_NM IS '장비명';
COMMENT ON COLUMN MESADM.TN_POS_EQP.EQP_CLS_ID IS '장비분류ID';
COMMENT ON COLUMN MESADM.TN_POS_EQP.SORTER_MODE_YN IS 'Sorter Mode 여부';
COMMENT ON COLUMN MESADM.TN_POS_EQP.STAT_CD IS '상태코드 [UP || DOWN || MAINT]  →  [RUN || IDLE || DOWN || MAINT]';
COMMENT ON COLUMN MESADM.TN_POS_EQP.PREV_STAT_CD IS '이전상태코드';
COMMENT ON COLUMN MESADM.TN_POS_EQP.STAT_CD_DT IS '상태코드일시';
COMMENT ON COLUMN MESADM.TN_POS_EQP.PREV_STAT_DT IS '이전상태일시';
COMMENT ON COLUMN MESADM.TN_POS_EQP.PROC_STAT_CD IS '프로세스상태코드 [RUN || IDLE || PAUSE]';
COMMENT ON COLUMN MESADM.TN_POS_EQP.PREV_PROC_STAT_CD IS '이전프로세스상태코드';
COMMENT ON COLUMN MESADM.TN_POS_EQP.PROC_STAT_CD_DT IS '프로세스상태코드일시';
COMMENT ON COLUMN MESADM.TN_POS_EQP.PREV_PROC_STAT_DT IS '이전프로세스상태일시';
COMMENT ON COLUMN MESADM.TN_POS_EQP.CTRL_MODE_CD IS '제어모드코드 [ONLINE-REMOTE || ONLINE-LOCAL || OFFLINE]';
COMMENT ON COLUMN MESADM.TN_POS_EQP.PREV_CTRL_MODE_CD IS '이전제어모드코드';
COMMENT ON COLUMN MESADM.TN_POS_EQP.CTRL_MODE_DT IS '제어모드일시';
COMMENT ON COLUMN MESADM.TN_POS_EQP.PREV_CTRL_MODE_DT IS '이전제어모드일시';
COMMENT ON COLUMN MESADM.TN_POS_EQP.OPRTN_MODE_CD IS '작업모드코드 [AUTO || SEMI || MANUAL]';
COMMENT ON COLUMN MESADM.TN_POS_EQP.PREV_OPRTN_MODE_CD IS '이전작업모드코드';
COMMENT ON COLUMN MESADM.TN_POS_EQP.OPRTN_MODE_DT IS '작업모드일시';
COMMENT ON COLUMN MESADM.TN_POS_EQP.PREV_OPRTN_MODE_DT IS '이전작업모드일시';
COMMENT ON COLUMN MESADM.TN_POS_EQP.PROC_LOT_CNT IS 'Processing Lot 수량';
COMMENT ON COLUMN MESADM.TN_POS_EQP.CPCT IS '용량';
COMMENT ON COLUMN MESADM.TN_POS_EQP.AUTO_DSP_YN IS '자동 반송 여부';
COMMENT ON COLUMN MESADM.TN_POS_EQP.INTLK_YN IS '인터락 여부';
COMMENT ON COLUMN MESADM.TN_POS_EQP.FNL_LOT_ID IS '최종 진행 LOT ID';
COMMENT ON COLUMN MESADM.TN_POS_EQP.SELF_INSP_YN IS '자주검사 진행여부';
COMMENT ON COLUMN MESADM.TN_POS_EQP.FNL_PROD_DEF_ID IS '최종 제품 코드 ID';
COMMENT ON COLUMN MESADM.TN_POS_EQP.RECIPE_ID IS 'Recipe ID';
COMMENT ON COLUMN MESADM.TN_POS_EQP.FNL_TKOUT_DT IS '최종 공정완료 시간(BRS_LOT_TRACK_OUT에서 저장)';
COMMENT ON COLUMN MESADM.TN_POS_EQP.MAINT_AFT_FST_YN IS 'MAINT 후 첫번째 여부(BRS_LOT_TRACK_IN_CNFM_REQ에서 선진행, 자주검사 여부 체크)';
COMMENT ON COLUMN MESADM.TN_POS_EQP.LOSS_STAT_CD IS '유실코드';
COMMENT ON COLUMN MESADM.TN_POS_EQP.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN MESADM.TN_POS_EQP.PREV_EVNT_NM IS '이전이벤트명';
COMMENT ON COLUMN MESADM.TN_POS_EQP.CSTM_EVNT_NM IS '커스텀이벤트명';
COMMENT ON COLUMN MESADM.TN_POS_EQP.PREV_CSTM_EVNT_NM IS '이전커스텀이벤트명';
COMMENT ON COLUMN MESADM.TN_POS_EQP.USE_STAT_CD IS '사용여부';
COMMENT ON COLUMN MESADM.TN_POS_EQP.RSN_CD IS '사유코드';
COMMENT ON COLUMN MESADM.TN_POS_EQP.TRNS_CM IS '트랜잭션설명';
COMMENT ON COLUMN MESADM.TN_POS_EQP.CRT_USER_ID IS '생성사용자ID';
COMMENT ON COLUMN MESADM.TN_POS_EQP.CRT_DT IS '생성일시';
COMMENT ON COLUMN MESADM.TN_POS_EQP.MDFY_USER_ID IS '변경사용자ID';
COMMENT ON COLUMN MESADM.TN_POS_EQP.MDFY_DT IS '변경일시';
COMMENT ON COLUMN MESADM.TN_POS_EQP.FNL_EVNT_DT IS '최종이벤트일시';
COMMENT ON COLUMN MESADM.TN_POS_EQP.TID IS '트랜잭션ID';
COMMENT ON COLUMN MESADM.TN_POS_EQP.FNL_PROC_SGMT_ID IS '마지막 진행 공정 ID';