-- MESADM.TN_RDS_EQP definition

CREATE TABLE "MESADM"."TN_RDS_EQP"
(	"OBJ_ID" VARCHAR2(100),
     "SITE_ID" VARCHAR2(40),
     "EQP_ID" VARCHAR2(40),
     "EQP_NM" VARCHAR2(40),
     "EQP_CLS_ID" VARCHAR2(40),
     "EQP_TYP" VARCHAR2(40),
     "PRNT_ID" VARCHAR2(40),
     "EQP_LVL_NO" NUMBER,
     "RUN_CNT" NUMBER,
     "RCP_ID" VARCHAR2(40),
     "ALRM_ID" VARCHAR2(40),
     "CPCT_UNIT_CD" VARCHAR2(40),
     "MAX_CPCT" NUMBER(20,10),
     "MIN_CPCT" NUMBER(20,10),
     "TACT_TM" NUMBER,
     "TACT_TM_UNIT_CD" VARCHAR2(40),
     "LEAD_TM" NUMBER,
     "LEAD_TM_UNIT_CD" VARCHAR2(40),
     "LCTN_NM" VARCHAR2(40),
     "PREV_LCTN_NM" VARCHAR2(40),
     "VNDR_ID" VARCHAR2(40),
     "MODEL_NO" VARCHAR2(40),
     "SRL_NO" VARCHAR2(40),
     "EC_SVR_NM" VARCHAR2(40),
     "MTRL_STK_TYP" VARCHAR2(40),
     "EQP_INLINE_ID" VARCHAR2(40),
     "EQP_INLINE_SEQ" NUMBER,
     "INLINE_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
     "BATCH_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
     "BATCH_CNT" NUMBER,
     "SORTER_MODE_AVAIL_YN" VARCHAR2(1),
     "MODEL_TYP" VARCHAR2(40),
     "UI_SEQ" NUMBER,
     "EVNT_NM" VARCHAR2(100),
     "PREV_EVNT_NM" VARCHAR2(100),
     "CSTM_EVNT_NM" VARCHAR2(100),
     "PREV_CSTM_EVNT_NM" VARCHAR2(100),
     "USE_STAT_CD" VARCHAR2(40),
     "RSN_CD" VARCHAR2(40),
     "TRNS_CM" VARCHAR2(4000),
     "CRT_USER_ID" VARCHAR2(40),
     "CRT_DT" TIMESTAMP (6),
     "MDFY_USER_ID" VARCHAR2(40),
     "MDFY_DT" TIMESTAMP (6) NOT NULL ENABLE,
     "FNL_EVNT_DT" TIMESTAMP (6),
     "TID" VARCHAR2(40),
     "LCTN_ID" VARCHAR2(40),
     "LINE_ID" VARCHAR2(40),
     "FLOOR_ID" VARCHAR2(40),
     "ZONE_ID" VARCHAR2(40),
     "AREA_ID" VARCHAR2(40),
     CONSTRAINT "PK_TN_RDS_EQP" PRIMARY KEY ("OBJ_ID")
);




COMMENT ON COLUMN MESADM.TN_RDS_EQP.OBJ_ID IS '오브젝트ID';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.SITE_ID IS '사이트ID';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.EQP_ID IS '장비ID';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.EQP_NM IS '장비명';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.EQP_CLS_ID IS '장비분류ID';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.EQP_TYP IS '장비타입';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.PRNT_ID IS '부모ID';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.EQP_LVL_NO IS '장비레벨번호';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.RUN_CNT IS '런수';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.RCP_ID IS '레시피ID';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.ALRM_ID IS '알람ID';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.CPCT_UNIT_CD IS '용량단위코드';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.MAX_CPCT IS '최대CAPACITY';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.MIN_CPCT IS '최소CAPACITY';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.TACT_TM IS '평균공정시간';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.TACT_TM_UNIT_CD IS '평균공정시간단위코드';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.LEAD_TM IS '리드타임';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.LEAD_TM_UNIT_CD IS '리드타임단위코드';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.LCTN_NM IS '소재지명';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.PREV_LCTN_NM IS '이전소재지명';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.VNDR_ID IS '벤더ID';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.MODEL_NO IS '모델번호';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.SRL_NO IS '연속번호';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.EC_SVR_NM IS '전자상거래서버명';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.MTRL_STK_TYP IS 'Material Stock Type [FROZEN || REFRIGERATED || AGINGTABLE]';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.EQP_INLINE_ID IS '인라인그룹ID';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.EQP_INLINE_SEQ IS '인라인진행순서';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.INLINE_YN IS '인라인장비여부';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.BATCH_YN IS '배치장비여부';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.BATCH_CNT IS '배치수량';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.SORTER_MODE_AVAIL_YN IS 'Sorter Mode 가능 여부';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.MODEL_TYP IS 'Model Type [BP_SINGLE || INOUT_SINGLE || BP_INLINE_SINGL || INOUT_INLINE_SINGLE || BP_BATCH || BP_BATCH_CHAMBER || INOUT_BATCH || INOUT_BATCH_CHAMBER]';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.UI_SEQ IS '단위순번';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.PREV_EVNT_NM IS '이전이벤트명';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.CSTM_EVNT_NM IS '커스텀이벤트명';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.PREV_CSTM_EVNT_NM IS '이전커스텀이벤트명';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.USE_STAT_CD IS '사용여부';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.RSN_CD IS '사유코드';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.TRNS_CM IS '트랜잭션설명';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.CRT_USER_ID IS '생성사용자ID';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.CRT_DT IS '생성일시';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.MDFY_USER_ID IS '변경사용자ID';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.MDFY_DT IS '변경일시';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.FNL_EVNT_DT IS '최종이벤트일시';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.TID IS '트랜잭션ID';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.LCTN_ID IS 'Location ID (GA-US, GUMI-KR)';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.LINE_ID IS 'Line ID (SVM, HVM)';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.FLOOR_ID IS 'Floor ID (!F, 2F, ...)';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.ZONE_ID IS 'Zone ID (CR1, CR2, CR3, ...)';
COMMENT ON COLUMN MESADM.TN_RDS_EQP.AREA_ID IS 'Area ID (A1, A2, A3, ...)';