-- MESADM.WN_MTRL_USAGE_INFO definition

CREATE TABLE "MESADM"."WN_MTRL_USAGE_INFO"
(	"OBJ_ID" VARCHAR2(100),
     "SITE_ID" VARCHAR2(40),
     "WORK_ID" VARCHAR2(40),
     "EQP_ID" VARCHAR2(40),
     "SUB_EQP_ID" VARCHAR2(40),
     "LOT_ID" VARCHAR2(40),
     "SPEC_ID" VARCHAR2(40),
     "SPEC_TYP" VARCHAR2(40),
     "SPEC_USE_CNT" NUMBER,
     "SPEC_LIMIT_CNT" NUMBER,
     "EVNT_NM" VARCHAR2(40),
     "PREV_EVNT_NM" VARCHAR2(100),
     "CSTM_EVNT_NM" VARCHAR2(100),
     "PREV_CSTM_EVNT_NM" VARCHAR2(100),
     "USE_STAT_CD" VARCHAR2(100),
     "RSN_CD" VARCHAR2(40),
     "TRNS_CM" VARCHAR2(4000),
     "CRT_USER_ID" VARCHAR2(40),
     "CRT_DT" TIMESTAMP (6),
     "MDFY_USER_ID" VARCHAR2(40),
     "MDFY_DT" TIMESTAMP (6),
     "FNL_EVNT_DT" TIMESTAMP (6),
     "TID" VARCHAR2(40),
     "POSN_ID" VARCHAR2(40),
     "SUB_SPEC_USE_CNT" NUMBER,
     CONSTRAINT "PK_WN_MTRL_USAGE_INFO" PRIMARY KEY ("OBJ_ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
         BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "TS_MES_IDX"  ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT" ;

CREATE UNIQUE INDEX "MESADM"."PK_WN_MTRL_USAGE_INFO" ON "MESADM"."WN_MTRL_USAGE_INFO" ("OBJ_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_IDX" ;

COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.OBJ_ID IS '오브젝트ID';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.SITE_ID IS '사이트 정보';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.WORK_ID IS 'Work ID';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.EQP_ID IS '장비ID';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.SUB_EQP_ID IS 'SUB장비ID';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.LOT_ID IS '로트ID';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.SPEC_ID IS '자재/치공구ID';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.SPEC_TYP IS '자재 타입 [ Durable | Material ]';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.SPEC_USE_CNT IS '사용 수량';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.SPEC_LIMIT_CNT IS '한계 수량';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.PREV_EVNT_NM IS '이전이벤트명';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.CSTM_EVNT_NM IS '커스텀이벤트명';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.PREV_CSTM_EVNT_NM IS '이전커스텀이벤트명';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.USE_STAT_CD IS '사용여부';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.RSN_CD IS '사유코드';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.TRNS_CM IS 'Event Comment';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.CRT_USER_ID IS '생성자';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.CRT_DT IS '생성일';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.MDFY_USER_ID IS 'Event 요청자';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.MDFY_DT IS 'Event 시간 ';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.FNL_EVNT_DT IS '최종이벤트일시';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.TID IS '트랜잭션ID';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.POSN_ID IS '위치ID';
COMMENT ON COLUMN MESADM.WN_MTRL_USAGE_INFO.SUB_SPEC_USE_CNT IS '실주행거리';