-- MESADM.WN_STATE_RULE_INFO definition

CREATE TABLE "MESADM"."WN_STATE_RULE_INFO"
(	"OBJ_ID" VARCHAR2(100),
     "SITE_ID" VARCHAR2(40),
     "RULE_NM" VARCHAR2(40),
     "TABLE_NM" VARCHAR2(40),
     "COLUMN_NM" VARCHAR2(40),
     "COLUMN_VAL" VARCHAR2(40),
     "COND_VAL" VARCHAR2(40),
     "RULE_DESC" VARCHAR2(4000),
     "EVNT_NM" VARCHAR2(40),
     "PREV_EVNT_NM" VARCHAR2(100),
     "CSTM_EVNT_NM" VARCHAR2(100),
     "PREV_CSTM_EVNT_NM" VARCHAR2(100),
     "USE_STAT_CD" VARCHAR2(100),
     "RSN_CD" VARCHAR2(40),
     "TRNS_CM" VARCHAR2(4000),
     "CRT_USER_ID" VARCHAR2(40),
     "CRT_DT" TIMESTAMP (6),
     "MDFY_USER_ID" VARCHAR2(40),
     "MDFY_DT" TIMESTAMP (6),
     "FNL_EVNT_DT" TIMESTAMP (6),
     "TID" VARCHAR2(40),
     CONSTRAINT "PK_WN_STATE_RULE_INFO" PRIMARY KEY ("OBJ_ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
         BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "TS_MES_IDX"  ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT" ;

CREATE UNIQUE INDEX "MESADM"."PK_WN_STATE_RULE_INFO" ON "MESADM"."WN_STATE_RULE_INFO" ("OBJ_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_IDX" ;
CREATE UNIQUE INDEX "MESADM"."UK_WN_STATE_RULE_INFO" ON "MESADM"."WN_STATE_RULE_INFO" ("SITE_ID", "RULE_NM", "TABLE_NM", "COLUMN_NM")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_IDX" ;

COMMENT ON COLUMN MESADM.WN_STATE_RULE_INFO.OBJ_ID IS '오브젝트ID';
COMMENT ON COLUMN MESADM.WN_STATE_RULE_INFO.SITE_ID IS '사이트 정보';
COMMENT ON COLUMN MESADM.WN_STATE_RULE_INFO.RULE_NM IS 'STATE Rule 명';
COMMENT ON COLUMN MESADM.WN_STATE_RULE_INFO.TABLE_NM IS '테이블명';
COMMENT ON COLUMN MESADM.WN_STATE_RULE_INFO.COLUMN_NM IS '컬럼명';
COMMENT ON COLUMN MESADM.WN_STATE_RULE_INFO.COLUMN_VAL IS '컬럼값';
COMMENT ON COLUMN MESADM.WN_STATE_RULE_INFO.COND_VAL IS '조건값(eq|ne|in|nin|lt|gt|lte|gte)';
COMMENT ON COLUMN MESADM.WN_STATE_RULE_INFO.RULE_DESC IS 'STATE Rule 설명';
COMMENT ON COLUMN MESADM.WN_STATE_RULE_INFO.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN MESADM.WN_STATE_RULE_INFO.PREV_EVNT_NM IS '이전이벤트명';
COMMENT ON COLUMN MESADM.WN_STATE_RULE_INFO.CSTM_EVNT_NM IS '커스텀이벤트명';
COMMENT ON COLUMN MESADM.WN_STATE_RULE_INFO.PREV_CSTM_EVNT_NM IS '이전커스텀이벤트명';
COMMENT ON COLUMN MESADM.WN_STATE_RULE_INFO.USE_STAT_CD IS '사용여부';
COMMENT ON COLUMN MESADM.WN_STATE_RULE_INFO.RSN_CD IS '사유코드';
COMMENT ON COLUMN MESADM.WN_STATE_RULE_INFO.TRNS_CM IS 'Event Comment';
COMMENT ON COLUMN MESADM.WN_STATE_RULE_INFO.CRT_USER_ID IS '생성자';
COMMENT ON COLUMN MESADM.WN_STATE_RULE_INFO.CRT_DT IS '생성일';
COMMENT ON COLUMN MESADM.WN_STATE_RULE_INFO.MDFY_USER_ID IS 'Event 요청자';
COMMENT ON COLUMN MESADM.WN_STATE_RULE_INFO.MDFY_DT IS 'Event 시간 ';
COMMENT ON COLUMN MESADM.WN_STATE_RULE_INFO.FNL_EVNT_DT IS '최종이벤트일시';
COMMENT ON COLUMN MESADM.WN_STATE_RULE_INFO.TID IS '트랜잭션ID';