-- MESADM.WN_SORTER_JOB_EXEC definition

CREATE TABLE "MESADM"."WN_SORTER_JOB_EXEC"
(	"OBJ_ID" VARCHAR2(100),
     "SITE_ID" VARCHAR2(40) NOT NULL ENABLE,
     "JOB_ID" VARCHAR2(40) NOT NULL ENABLE,
     "EQP_ID" VARCHAR2(40),
     "SRC_LOT_ID" VARCHAR2(40),
     "TGT_LOT_ID" VARCHAR2(40),
     "SRC_CARR_ID" VARCHAR2(40),
     "SRC_SLOT_NO" VARCHAR2(100),
     "SRC_PROD_MTRL_ID" VARCHAR2(4000),
     "TGT_CARR_ID" VARCHAR2(40),
     "TGT_SLOT_NO" VARCHAR2(100),
     "TGT_PROD_MTRL_ID" VARCHAR2(4000),
     "PRIRT_NO" NUMBER,
     "SORTER_JOB_TYP" VARCHAR2(40),
     "DTL_SORTER_JOB_TYP" VARCHAR2(40),
     "JOB_STAT_CD" VARCHAR2(40),
     "PROC_SGMT_ID" VARCHAR2(40),
     "PROC_SGMT_SEQ" NUMBER,
     "MDFY_USER_ID" VARCHAR2(40),
     "MDFY_DT" TIMESTAMP (6),
     "CRT_USER_ID" VARCHAR2(40),
     "CRT_DT" TIMESTAMP (6),
     "CSTM_EVNT_NM" VARCHAR2(100),
     "EVNT_NM" VARCHAR2(100),
     "FNL_EVNT_DT" TIMESTAMP (6),
     "PREV_CSTM_EVNT_NM" VARCHAR2(100),
     "PREV_EVNT_NM" VARCHAR2(100),
     "RSN_CD" VARCHAR2(40),
     "TID" VARCHAR2(40),
     "TRNS_CM" VARCHAR2(4000),
     "USE_STAT_CD" VARCHAR2(40)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT" ;
CREATE UNIQUE INDEX "MESADM"."PK_WN_SORTER_JOB_EXEC" ON "MESADM"."WN_SORTER_JOB_EXEC" ("OBJ_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_IDX" ;
ALTER TABLE "MESADM"."WN_SORTER_JOB_EXEC" ADD CONSTRAINT "PK_WN_SORTER_JOB_EXEC" PRIMARY KEY ("OBJ_ID")
    USING INDEX "MESADM"."PK_WN_SORTER_JOB_EXEC"  ENABLE;

CREATE UNIQUE INDEX "MESADM"."PK_WN_SORTER_JOB_EXEC" ON "MESADM"."WN_SORTER_JOB_EXEC" ("OBJ_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_IDX" ;
CREATE UNIQUE INDEX "MESADM"."UK_WN_SORTER_JOB_EXEC" ON "MESADM"."WN_SORTER_JOB_EXEC" ("SITE_ID", "JOB_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_IDX" ;

COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.OBJ_ID IS '오브젝트ID';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.SITE_ID IS '사이트 정보';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.JOB_ID IS 'Job ID';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.EQP_ID IS 'Sorter 설비 ID';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.SRC_LOT_ID IS '소스 LOT ID';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.TGT_LOT_ID IS '대상 LOT ID';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.SRC_CARR_ID IS '소스 CARR ID';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.SRC_SLOT_NO IS '소스 SLOT 번호';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.SRC_PROD_MTRL_ID IS '소스 PROD MTRL ID';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.TGT_CARR_ID IS '대상 CARR ID';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.TGT_SLOT_NO IS '대상 SLOT 번호';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.TGT_PROD_MTRL_ID IS '대상 PROD MTRL ID';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.PRIRT_NO IS '우선 순위 번호';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.SORTER_JOB_TYP IS '소터 작업 타입';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.DTL_SORTER_JOB_TYP IS '상세 소터 작업 타입';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.JOB_STAT_CD IS 'Sorter Job 상태 코드';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.PROC_SGMT_ID IS '프로세스세그먼트ID';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.PROC_SGMT_SEQ IS '프로세스세그먼트 순번';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.MDFY_USER_ID IS '수정자';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.MDFY_DT IS '수정일';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.CRT_USER_ID IS '생성자';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.CRT_DT IS '생성일';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.CSTM_EVNT_NM IS '커스텀이벤트명';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.FNL_EVNT_DT IS '최종이벤트일시';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.PREV_CSTM_EVNT_NM IS '이전커스텀이벤트명';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.PREV_EVNT_NM IS '이전이벤트명';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.RSN_CD IS '사유코드';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.TID IS '트랜잭션ID';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.TRNS_CM IS 'Event Comment';
COMMENT ON COLUMN MESADM.WN_SORTER_JOB_EXEC.USE_STAT_CD IS '사용여부';