-- MESADM.WN_WIP_STAT definition

CREATE TABLE "MESADM"."WN_WIP_STAT"
(	"OBJ_ID" VARCHAR2(100),
     "SITE_ID" VARCHAR2(40),
     "LOT_ID" VARCHAR2(40),
     "CARR_ID" VARCHAR2(40),
     "CARR_LCTN_NM" VARCHAR2(40),
     "WORK_STAT_CD" VARCHAR2(40),
     "DTL_WORK_STAT_CD" VARCHAR2(40),
     "MDFY_USER_ID" VARCHAR2(40),
     "MDFY_DT" TIMESTAMP (6),
     "CRT_USER_ID" VARCHAR2(40),
     "CRT_DT" TIMESTAMP (6),
     "CSTM_EVNT_NM" VARCHAR2(255 CHAR),
     "EVNT_NM" VARCHAR2(255 CHAR),
     "FNL_EVNT_DT" TIMESTAMP (6),
     "PREV_CSTM_EVNT_NM" VARCHAR2(255 CHAR),
     "PREV_EVNT_NM" VARCHAR2(255 CHAR),
     "RSN_CD" VARCHAR2(255 CHAR),
     "TID" VARCHAR2(255 CHAR),
     "TRNS_CM" VARCHAR2(255 CHAR),
     "USE_STAT_CD" VARCHAR2(255 CHAR),
     "CRNT_EQP_ID" VARCHAR2(40),
     "CRNT_PORT_ID" VARCHAR2(40),
     "BATCH_ID" VARCHAR2(40),
     "RESV_EQP_ID" VARCHAR2(40),
     "RESV_PORT_ID" VARCHAR2(40),
     "EQP_CHK_YN" VARCHAR2(1),
     "RCP_CHK_YN" VARCHAR2(1),
     "TRACK_IN_CNFM_YN" VARCHAR2(1),
     "RESV_GRP_ID" VARCHAR2(40),
     "BATCH_SEQ" VARCHAR2(40),
     "SELF_INSP_INFO_OBJ_ID" VARCHAR2(100),
     "SELF_INSP_YN" VARCHAR2(1),
     "SELF_INSP_PANEL_CNT" NUMBER,
     "RESV_OUT_PORT_ID" VARCHAR2(40),
     "RESV_OUT_CARR_ID" VARCHAR2(40),
     "SMPL_LOT_YN" VARCHAR2(1),
     "SMPL_WORK_TYP" VARCHAR2(40),
     "SMPL_QTY" NUMBER,
     "MOVE_STAT_CD" VARCHAR2(40),
     CONSTRAINT "PK_WN_WIP_STAT" PRIMARY KEY ("OBJ_ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
         BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "TS_MES_IDX"  ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT" ;

CREATE UNIQUE INDEX "MESADM"."PK_WN_WIP_STAT" ON "MESADM"."WN_WIP_STAT" ("OBJ_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_IDX" ;
CREATE UNIQUE INDEX "MESADM"."UK_WN_WIP_STAT" ON "MESADM"."WN_WIP_STAT" ("SITE_ID", "LOT_ID", "CARR_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_IDX" ;

COMMENT ON COLUMN MESADM.WN_WIP_STAT.OBJ_ID IS '오브젝트ID';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.SITE_ID IS '사이트 정보';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.LOT_ID IS 'Lot ID';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.CARR_ID IS 'Carrier ID';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.CARR_LCTN_NM IS 'Carrier 위치명';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.WORK_STAT_CD IS '재공 상태 코드';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.DTL_WORK_STAT_CD IS '상세 재공 상태 코드';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.MDFY_USER_ID IS '수정자';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.MDFY_DT IS '수정일';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.CRT_USER_ID IS '생성자';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.CRT_DT IS '생성일';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.CRNT_EQP_ID IS '현재 EQP ID';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.CRNT_PORT_ID IS '현재 PORT ID';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.BATCH_ID IS '배치 ID';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.RESV_EQP_ID IS 'Dispatching 예약 EQP ID';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.RESV_PORT_ID IS 'Dispatching 예약 PORT ID';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.EQP_CHK_YN IS 'EQP 체크 여부';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.RCP_CHK_YN IS 'Recipe 체크 여부';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.TRACK_IN_CNFM_YN IS 'Track In 가능 여부';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.RESV_GRP_ID IS 'Dispatching Group ID - Batch, InOut';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.BATCH_SEQ IS '배치 SEQ';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.SELF_INSP_INFO_OBJ_ID IS '자주검사 OBJ_ID';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.SELF_INSP_YN IS '자주검사 여부';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.SELF_INSP_PANEL_CNT IS '자주검사 패널 수량';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.RESV_OUT_PORT_ID IS 'Dispatching Out Port ID';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.RESV_OUT_CARR_ID IS 'Dispatching Out Carrier ID';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.SMPL_LOT_YN IS '샘플 LOT 여부';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.SMPL_WORK_TYP IS '샘플 WORK 타입';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.SMPL_QTY IS '샘플 수량';
COMMENT ON COLUMN MESADM.WN_WIP_STAT.MOVE_STAT_CD IS '반송 상태 코드';