-- MESADM.WN_ZONE definition

CREATE TABLE "MESADM"."WN_ZONE"
(	"OBJ_ID" VARCHAR2(100),
     "SITE_ID" VARCHAR2(40),
     "ZONE_ID" VARCHAR2(40),
     "ZONE_TYP" VARCHAR2(64),
     "MANL_YN" VARCHAR2(40),
     "MAX_CPCT_VAL" NUMBER(20,0),
     "CRNT_CPCT_VAL" NUMBER(20,0),
     "CARR_TYP" VARCHAR2(64),
     "MDFY_USER_ID" VARCHAR2(40),
     "MDFY_DT" TIMESTAMP (6),
     "CRT_USER_ID" VARCHAR2(40),
     "CRT_DT" TIMESTAMP (6),
     "CSTM_EVNT_NM" VARCHAR2(255 CHAR),
     "EVNT_NM" VARCHAR2(255 CHAR),
     "FNL_EVNT_DT" TIMESTAMP (6),
     "PREV_CSTM_EVNT_NM" VARCHAR2(255 CHAR),
     "PREV_EVNT_NM" VARCHAR2(255 CHAR),
     "RSN_CD" VARCHAR2(255 CHAR),
     "TID" VARCHAR2(255 CHAR),
     "TRNS_CM" VARCHAR2(255 CHAR),
     "USE_STAT_CD" VARCHAR2(255 CHAR),
     "FACILITY_ID" VARCHAR2(40),
     "EQP_ID" VARCHAR2(40),
     CONSTRAINT "PK_WN_ZONE" PRIMARY KEY ("OBJ_ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
         BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "TS_MES_IDX"  ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT" ;

CREATE UNIQUE INDEX "MESADM"."PK_WN_ZONE" ON "MESADM"."WN_ZONE" ("OBJ_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_IDX" ;

COMMENT ON TABLE MESADM.WN_ZONE IS '반송을 위한 Zone 구획한 테이블';
COMMENT ON COLUMN MESADM.WN_ZONE.OBJ_ID IS '오브젝트ID';
COMMENT ON COLUMN MESADM.WN_ZONE.SITE_ID IS '사이트 정보';
COMMENT ON COLUMN MESADM.WN_ZONE.ZONE_ID IS 'ZONE ID';
COMMENT ON COLUMN MESADM.WN_ZONE.ZONE_TYP IS 'ZONE 타입';
COMMENT ON COLUMN MESADM.WN_ZONE.MANL_YN IS '매뉴얼 여부';
COMMENT ON COLUMN MESADM.WN_ZONE.MAX_CPCT_VAL IS 'Max Capacity';
COMMENT ON COLUMN MESADM.WN_ZONE.CRNT_CPCT_VAL IS 'Current Capacity';
COMMENT ON COLUMN MESADM.WN_ZONE.CARR_TYP IS 'Carrier 타입';
COMMENT ON COLUMN MESADM.WN_ZONE.EQP_ID IS 'Equipment ID';