-- MESADM.WN_WORK_STAT definition

CREATE TABLE "MESADM"."WN_WORK_STAT"
(	"OBJ_ID" VARCHAR2(100),
     "SITE_ID" VARCHAR2(40),
     "WORK_ID" VARCHAR2(40),
     "EQP_ID" VARCHAR2(40),
     "WORK_STAT_CD" VARCHAR2(40),
     "WORK_START_TM" TIMESTAMP (6),
     "WORK_QTY" NUMBER(20,0),
     "FNL_TASK_NM" VARCHAR2(40),
     "BATCH_YN" VARCHAR2(1),
     "INLINE_YN" VARCHAR2(1),
     "EVNT_NM" VARCHAR2(40),
     "PREV_EVNT_NM" VARCHAR2(100),
     "CSTM_EVNT_NM" VARCHAR2(100),
     "PREV_CSTM_EVNT_NM" VARCHAR2(100),
     "USE_STAT_CD" VARCHAR2(100),
     "RSN_CD" VARCHAR2(40),
     "TRNS_CM" VARCHAR2(4000),
     "CRT_USER_ID" VARCHAR2(40),
     "CRT_DT" TIMESTAMP (6),
     "MDFY_USER_ID" VARCHAR2(40),
     "MDFY_DT" TIMESTAMP (6),
     "FNL_EVNT_DT" TIMESTAMP (6),
     "TID" VARCHAR2(40),
     "EQP_INLINE_ID" VARCHAR2(40),
     "INLINE_STAT_CD" VARCHAR2(40),
     "DSP_WORK_ID" VARCHAR2(40),
     CONSTRAINT "PK_WN_WORK_STAT" PRIMARY KEY ("OBJ_ID")
);

COMMENT ON COLUMN MESADM.WN_WORK_STAT.OBJ_ID IS '오브젝트ID';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.SITE_ID IS '사이트 정보';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.WORK_ID IS 'Work ID';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.EQP_ID IS 'Equipment ID';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.WORK_STAT_CD IS '작업 상태 코드';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.WORK_START_TM IS '작업 시작 시간';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.WORK_QTY IS '작업 수량 Lot QTY';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.FNL_TASK_NM IS '최종태스크명';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.BATCH_YN IS '배치여부';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.INLINE_YN IS '인라인여부';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.PREV_EVNT_NM IS '이전이벤트명';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.CSTM_EVNT_NM IS '커스텀이벤트명';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.PREV_CSTM_EVNT_NM IS '이전커스텀이벤트명';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.USE_STAT_CD IS '사용여부';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.RSN_CD IS '사유코드';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.TRNS_CM IS 'Event Comment';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.CRT_USER_ID IS '생성자';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.CRT_DT IS '생성일';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.MDFY_USER_ID IS 'Event 요청자';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.MDFY_DT IS 'Event 시간 ';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.FNL_EVNT_DT IS '최종이벤트일시';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.TID IS '트랜잭션ID';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.EQP_INLINE_ID IS 'EQP INLINE ID';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.INLINE_STAT_CD IS 'EQP INLINE 상태 코드';
COMMENT ON COLUMN MESADM.WN_WORK_STAT.DSP_WORK_ID IS 'Dispatching Work ID';