-- MESADM.WN_WORK_JOB definition

CREATE TABLE "MESADM"."WN_WORK_JOB"
(	"OBJ_ID" VARCHAR2(100),
     "SITE_ID" VARCHAR2(40),
     "WORK_ID" VARCHAR2(40),
     "JOB_SEQ_ID" VARCHAR2(40),
     "LOT_ID" VARCHAR2(40),
     "BATCH_ID" VARCHAR2(40),
     "CRNT_CARR_ID" VARCHAR2(40),
     "IN_PORT_ID" VARCHAR2(40),
     "IN_CARR_ID" VARCHAR2(40),
     "IN_CARR_TYP" VARCHAR2(40),
     "OUT_PORT_ID" VARCHAR2(40),
     "OUT_CARR_ID" VARCHAR2(40),
     "OUT_CARR_TYP" VARCHAR2(40),
     "PROD_DEF_ID" VARCHAR2(40),
     "PROC_DEF_ID" VARCHAR2(40),
     "PROC_SGMT_ID" VARCHAR2(40),
     "JOB_QTY" NUMBER(20,0),
     "RCP_DEF_ID" VARCHAR2(40),
     "RCP_READY_YN" VARCHAR2(1),
     "JOB_STAT_CD" VARCHAR2(40),
     "EVNT_NM" VARCHAR2(40),
     "PREV_EVNT_NM" VARCHAR2(100),
     "CSTM_EVNT_NM" VARCHAR2(100),
     "PREV_CSTM_EVNT_NM" VARCHAR2(100),
     "USE_STAT_CD" VARCHAR2(100),
     "RSN_CD" VARCHAR2(40),
     "TRNS_CM" VARCHAR2(4000),
     "CRT_USER_ID" VARCHAR2(40),
     "CRT_DT" TIMESTAMP (6),
     "MDFY_USER_ID" VARCHAR2(40),
     "MDFY_DT" TIMESTAMP (6),
     "FNL_EVNT_DT" TIMESTAMP (6),
     "TID" VARCHAR2(40),
     "WORK_FACE_CD" VARCHAR2(40),
     CONSTRAINT "PK_WN_WORK_JOB" PRIMARY KEY ("OBJ_ID")
);

COMMENT ON COLUMN MESADM.WN_WORK_JOB.OBJ_ID IS '오브젝트ID';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.SITE_ID IS '사이트 정보';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.WORK_ID IS 'Work ID';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.JOB_SEQ_ID IS '작업 순번 ID';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.LOT_ID IS 'LOT ID';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.BATCH_ID IS 'BATCH ID';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.CRNT_CARR_ID IS '현재 CARRIER ID';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.IN_PORT_ID IS 'Input Port ID';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.IN_CARR_ID IS 'Input Carrier ID';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.IN_CARR_TYP IS 'Carrier Type';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.OUT_PORT_ID IS 'Output Port ID';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.OUT_CARR_ID IS 'Output Carrier ID';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.OUT_CARR_TYP IS 'Carrier Type';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.PROD_DEF_ID IS '제품정의ID';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.PROC_DEF_ID IS '프로세스정의ID';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.PROC_SGMT_ID IS '프로세스세그먼트ID';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.JOB_QTY IS '작업 수량';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.RCP_DEF_ID IS '레시피정의ID';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.RCP_READY_YN IS 'RMS 레시피 확인 여부';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.JOB_STAT_CD IS '작업 상태 코드';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.PREV_EVNT_NM IS '이전이벤트명';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.CSTM_EVNT_NM IS '커스텀이벤트명';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.PREV_CSTM_EVNT_NM IS '이전커스텀이벤트명';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.USE_STAT_CD IS '사용여부';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.RSN_CD IS '사유코드';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.TRNS_CM IS 'Event Comment';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.CRT_USER_ID IS '생성자';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.CRT_DT IS '생성일';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.MDFY_USER_ID IS 'Event 요청자';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.MDFY_DT IS 'Event 시간 ';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.FNL_EVNT_DT IS '최종이벤트일시';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.TID IS '트랜잭션ID';
COMMENT ON COLUMN MESADM.WN_WORK_JOB.WORK_FACE_CD IS '작업면 코드(TTT:N, TBT:Y)';